# @package _global_

hydra:
  run:
    dir: .

defaults:
  - _self_ # this first, so that the base config can be overridden by others
  
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

base_dir: /workspace
model_path: ${base_dir}/models
data_path: ${base_dir}
log_dir: ${base_dir}/logs
seed: 42

run_name: image_classification_cifar10
id:
model_name: image_classification

mixup:
  mixup_alpha: 0.8
  cutmix_alpha: 1.0
  cutmix_minmax: # None
  prob: 0.9
  switch_prob: 0.5
  mode: batch
  label_smoothing: 0.1
  num_classes: 10

model:
  model_path: /workspace/models/image_kd/model-50040-0.0845-val.ckpt
  model_name: image_kd
  linear_classifier: False
  num_classes: 10

  layer_decay: 0.75

  prediction_mode: mean_pooling

data:
  _name: cifar10
  aa: rand-m9-mstd0.5-inc1
  reprob: 0.25
  remode: pixel
  recount: 1

  data_path: ${data_path}
  batch_size: 256
  num_workers: 8
  shuffle: True
  drop_last: True

optimizer:
  lr: 0.001
  betas: [0.9, 0.999]
  eps: 1e-8
  weight_decay: 0.01
  max_steps: 3525

lightning_trainer:
  default_root_dir: ${log_dir}
  accelerator: gpu
  devices: -1
  strategy: auto # auto -> default
  max_epochs: 15
  num_sanity_val_steps: 0
  precision: 16-mixed
  log_every_n_steps: 50
