# @package _global_

hydra:
  run:
    dir: .

defaults:
  - _self_ # this first, so that the base config can be overridden by others
  
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

base_dir: /workspace
model_path: ${base_dir}/models
data_path: ${base_dir}
log_dir: ${base_dir}/logs
seed: 42

run_name: text_classification_stsb
id:
model_name: text_classification

metric: spearman
regression: True

model:
  model_path:
  model_name: text_kd
  num_classes: 1
  dropout: 0.1

data:
  _name: stsb_glue
  num_max_bpe_tokens: 256

  data_path: ${data_path}
  batch_size: 16
  num_workers: 5
  shuffle: True
  drop_last: True

optimizer:
  lr: 4e-5
  betas: [0.9,0.98]
  eps: 1e-06
  weight_decay: 0.1
  max_steps: 7187

lightning_trainer:
  default_root_dir: ${log_dir}
  accelerator: gpu
  devices: -1
  strategy: auto # auto -> default
  max_epochs: 20
  precision: 16-mixed
  log_every_n_steps: 50
