# @package _global_

hydra:
  run:
    dir: .

defaults:
  - _self_ # this first, so that the base config can be overridden by others
  
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

base_dir: "/workspace"
model_path: ${base_dir}/models
data_path: ${base_dir}
log_dir: ${base_dir}/logs
seed: 42

run_name: text_kd
id:
model_name: text_kd

load_checkpoint:

model:
  depth: 6

data:
  _name: masked_lm # dataset name

  name: openwebtext # name of the (masked) language modeling dataset
  data_path: /workspace
  text_file: /workspace/openwebtext.txt
  block_size: 256
  mask_prob: 0.0

  batch_size: 256
  num_workers: 8
  shuffle: True
  drop_last: True


checkpoint:
  common:
    dirpath: ${model_path}/${run_name}
    enable_version_counter: False
    every_n_epochs: 1
    save_on_train_epoch_end: False # False -> run at end of validation
    verbose: True
    auto_insert_metric_name: False

  checkpoints:
    - monitor: val/loss
      mode: min
      filename: model-{step}-{${.monitor}:.4f}-val

    - monitor: train/loss
      mode: min
      filename: model-{step}-{${.monitor}:.4f}-train

optimizer:
  base_lr: 0.0005
  betas: [ 0.9,0.98 ]
  eps: 1e-06
  weight_decay: 0.01
  max_steps: 60000

lightning_trainer:
  default_root_dir: ${log_dir}
  accelerator: gpu
  devices: -1
  max_steps: 60000
  val_check_interval: 6000
  precision: 16-mixed
  log_every_n_steps: 50

  ddp:
    gradient_as_bucket_view: True # optimizes memory usage
    static_graph: True # optimizes memory usage
