
pretrained_path: /workspace/models/

d2v_image_path: ${pretrained_path}base_imagenet.pt
d2v_text_path: ${pretrained_path}workspace/models/nlp_base.pt

model_version:
model_name: Sx3HRe

filip_zero_shot: True

data:
  num_max_bpe_tokens: 64
  imagenet:
    data_path: /workspace
    pretraining: True
    batch_size: 256
    num_workers: 4
    shuffle: False
    drop_last: False
