# @package _global_

hydra:
  run:
    dir: .

defaults:
  - _self_ # this first, so that the base config can be overridden by others
  
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

seed: 42
n_epochs: 10
save_path: /workspace/models/cluster.pt

model:
  beitv2:
    model_path: /workspace/models
    model_name: beitv2_base_patch16_224_pt1k.pth
    drop_path_rate: 0.1
    use_shared_rel_pos_bias: True
    use_abs_pos_emb: False
    vocab_size: 8192
    init_values: 0.1

  num_clusters: 1024
  decay: 0.95

data:
  dataloader:
    batch_size: 512
    num_workers: 8
    shuffle: True
    drop_last: True

  common: # keys used for all datasets
    data_path: /workspace
    num_max_bpe_tokens: 64
    color_jitter: # None
    beit_transforms: False
    crop_scale: [0.7, 1.0]
    text_token_mask_prob: 0.0

  datamodules:
    coco_captions:
      task: captioning

    conceptual_captions_3m: {}

    conceptual_captions_12m: {}
