hydra:
  run:
    dir: .

defaults:
  - _self_ # this first, so that the base config can be overridden by others
  - datamodule: text
  
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

model_path: /workspace/models
data_path: /workspace

out_path: ${data_path}
offset: 0 # number of batches of the dataset already created

datamodule:
  _name: ???
  model_state_dict: ???
  
  data_path: ${data_path}

  batch_size: 256 # 512
  num_workers: 5
  shuffle: False
  drop_last: False
