# @package _group_

hydra:
  run:
    dir: .

defaults:
  - _self_ # this first, so that the base config can be overridden by others
  - datamodule: text

model_state_dict: ???

datamodule:
  _name: ???

  data_path: ../../data

  batch_size: 256
  num_workers: 5
  shuffle: False
  drop_last: False
