# @package _group_

hydra:
  run:
    dir: .

defaults:
  - _self_ # this first, so that the base config can be overridden by others
  - datamodule: text
  
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog



datamodule:
  _name: ???
  model_state_dict: ???
  
  data_path: ../data

  batch_size: 256
  num_workers: 5
  shuffle: False
  drop_last: False
